###Welcome
GET http://localhost:3000

###Get a list of all users
GET http://localhost:3000/api/users

### Create a users
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "name": "John Smith",
  "age": "40",
  "country": "USA"
}

### GET a product by id
GET http://localhost:3000/api/users/c6ec4eb5-0f85-4ec8-895c-8dfbdbf1a12b

### Update a product by id
PUT  http://localhost:3000/api/users/8e8e165b-caa3-4e67-9f89-bdb4114c451f
Content-Type: application/json

{
  "name": "Heinrich",
  "age": "55",
  "country": "GER"
}


### Delete a product by id
DELETE  http://localhost:3000/people/5df118b3c86e5826958b661a

### 404 route Not Found
GET http://localhost:3000/abc_xyz



































#hrXWgw4Q127uqZJ3